version: '3'
services:
  Ionic1:
    container_name: ionic1
    build: .
    image: michalsindler/ionic:ionic1
    ports:
     - "8100:8100"
     - "35729:35729"
     - "5037:5037"
    volumes:
     - ./../:/myApp:rw